### ISSUE TITLE
Update 3.5.10 and 3.5.11 brokes ServiceEvent in discovery

### ISSUE THREAD

**Issue by GazimSoliev** [jmdns/jmdns#281] opened 2024-08-07 15:17 UTC
ServiceEvent in discovery gives wrong info about service, for example empty addresses (ServiceEvent.info.hostAddresses) and wrong hostname from field "ServiceEvent.info.server"

**Comment by kaikreuzer** [comment] 2024-08-08 08:49
@Siedlerchr, @ivenhov, @plotczyktest & @joerg1985: You are the contributors of the changes to these releases - does any of you have an idea, what change could cause this regression and how to fix it?

**Comment by kaikreuzer** [comment] 2024-08-08 08:50
@GazimSoliev Can you maybe provide some more details on the issue like e.g. a concrete example of what is "wrong"?

**Comment by Siedlerchr** [comment] 2024-08-08 11:11
Without any more details it's hard to judge here what is wrong or not. 
My changes did not affect the content of the ServiceInfo message itself, and I am using it for an IPP printer server without any problems

**Comment by GazimSoliev** [comment] 2024-08-08 13:08
Tested in Kotlin Multiplatform 2.0.0, target JVM and Android JVM. In this test I caught that JmDNS can't resolve service in version 3.5.11, but in 3.5.9 everything works.
dependecies:
org.jmdns:jmdns:3.5.11
org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0-RC
org.jetbrains.kotlin:kotlin-test:2.0.0

```
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import java.net.Inet4Address
import java.net.Inet6Address
import java.net.InetAddress
import java.net.NetworkInterface
import javax.jmdns.JmDNS
import javax.jmdns.ServiceEvent
import javax.jmdns.ServiceInfo
import javax.jmdns.ServiceListener
import kotlin.test.*

class CheckJmDNS {
    private val iPv4Address = getIPAddressInLan()
    private val hostname = "hostname-test"
    private val type = "_http._tcp.local."
    private val name = "example"
    private val port = 1234
    private lateinit var jmdns: JmDNS
    private val deferredInfo = CompletableDeferred<ServiceInfo>()

    @BeforeTest
    fun createJmdns() {
        jmdns = JmDNS.create(iPv4Address, hostname)
        val serviceInfo = ServiceInfo.create(type, name, port, "path=index.html")
        val listener = object : ServiceListener {
            override fun serviceAdded(event: ServiceEvent?) {
                println("Added service: $event")
            }

            override fun serviceRemoved(event: ServiceEvent?) {
                println("Removed service: $event")
            }

            override fun serviceResolved(event: ServiceEvent?) {
                println("Resolved service: $event")
                if (event?.name != name) return
                deferredInfo.complete(event.info)
            }
        }
        jmdns.registerService(serviceInfo)
        jmdns.addServiceListener(type, listener)
    }

    @Test
    fun `should have addresses and correct hostname`() {
        runBlocking {
            val result = withTimeout(30_000) { deferredInfo.await() }

            val hosts = result.hostAddresses.toList()
            println("Hosts: $hosts")
            assertContains(hosts, iPv4Address?.hostAddress)

            val expectedHostname = "$hostname.local."
            val actualHostname = result.server
            println("Hostname: $actualHostname")
            assertEquals(expectedHostname, actualHostname)
        }
    }

    @AfterTest
    fun closeJmdns() {
        jmdns.close()
    }

    private fun getIPAddressesInLan(ipv4: Boolean = true): List<InetAddress> {
        val lanAddresses =
            getIPAddresses().filter {
                val firstCondition = !it.isLoopbackAddress
                val secondCondition = if (ipv4) it is Inet4Address else it is Inet6Address
                firstCondition && secondCondition
            }
        return lanAddresses
    }

    private fun getIPAddresses(): List<InetAddress> {
        val interfaces = NetworkInterface.getNetworkInterfaces().toList()
        val addresses = interfaces.flatMap { it.inetAddresses.toList() }
        return addresses
    }

    private fun getIPAddressInLan(ipv4: Boolean = true) = getIPAddressesInLan(ipv4).firstOrNull()
}
```

**Comment by GazimSoliev** [comment] 2024-08-08 13:10
I've created this test now, and I've noticed different problem - Service resolves so long, more than 30 seconds, tested in MacOS, Windows, and Android.

**Comment by gjvanderheiden** [comment] 2024-08-16 10:41
Same issue here, works fine on version 3.5.9, not so much on 3.5.10 and 3.5.11.
I am able to search a service I started with avahi on linux.

**Comment by joerg1985** [comment] 2024-08-16 11:04
Could you share some code to reproduce the issue?

**Comment by gjvanderheiden** [comment] 2024-08-16 13:10
[test-jmdns.tar.gz](https://github.com/user-attachments/files/16637420/test-jmdns.tar.gz)
Stripped all code non relevant to jmdns. No rocket science here. Change version number in the pom so see difference.

**Comment by gjvanderheiden** [comment] 2024-08-16 13:12
I stopped local avahi service to avoid interference. Also tried all kinds of variants of InetAddress, no sigar.

**Comment by joerg1985** [comment] 2024-08-18 18:04
@gjvanderheiden i just had a look, but i get the identical results for 3.5.9 / 3.5.10 / 3.5.11.
I did run `JmdnsTest` first and then `ServiceDiscovery`, the output of `ServiceDiscovery` is every time the same.

This is the output of 3.5.1:
```
/usr/lib/jvm/java-17-openjdk/bin/java -javaagent:/home/joerg/.local/share/JetBrains/Toolbox/apps/intellij-idea-community-edition/lib/idea_rt.jar=40649:/home/joerg/.local/share/JetBrains/Toolbox/apps/intellij-idea-community-edition/bin -Dfile.encoding=UTF-8 -classpath /home/joerg/Downloads/test-jmdns/target/classes:/home/joerg/.m2/repository/org/slf4j/slf4j-api/2.0.12/slf4j-api-2.0.12.jar:/home/joerg/.m2/repository/org/jmdns/jmdns/3.5.11/jmdns-3.5.11.jar jmdnstest.ServiceDiscovery
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
\00
konijn
konijn._hap._tcp.local.
hap

Process finished with exit code 0
```

**Comment by gjvanderheiden** [comment] 2024-08-20 09:11
I gave it some more attention. Turns out that I can restart 3.5.9 the publisher and the discovery pretty fast. 3.5.11 seems to need some more time. I'm using  jmdns in a series of integration tests, the tests start up de server (publisher) with jmdns and the discovery (also jmdns). Just like the stripped down example. I did try some wait time in my integration tests, but turns out it just wasn't enough. 5 seconds between publish method and starting the client works.

**Comment by gjvanderheiden** [comment] 2024-08-20 09:45
@joerg1985 I ran some more tests. If I use 3.5.11 (didn't test with 3.5.10) and I start both the first time it works. If I restart the publisher and then run the discovery, no answer. Let the publisher run and restart the discovery, it works again. Tried closing jmdns with a shutdownhook in the publisher, no difference. With 3.5.9 I can hit restart all day long (theoretically)

Arch Linux, openjdk22, IPv4 and IPv6 running, no firewall on the machine I test on (same machine anyway).

**Comment by gjvanderheiden** [comment] 2024-08-20 13:20
I have a suite of integration tests where I spin up the server from the tests (Java) and discover them with a testclient. It always fails, even if I wait for 15 seconds (Thread.sleep()) between the server started(publish) and the tests with the client (discover).

**Comment by gjvanderheiden** [comment] 2024-08-20 14:05
[test-jmdns.tar.gz](https://github.com/user-attachments/files/16676862/test-jmdns.tar.gz)
Changed the code to something simple. I have multiple bonjour services on my lan, 5 are HAP. 4 of them are published with jmdns 3.5.9 (on freebsd). 1 of them is a commercial one, it's a Hunter Douglass / Luxaflex curtains HUB. If I run discovery, I always get the jmdns ones, sometimes the commercial one. When I also start the test (ServicePublisher.java) I sometimes get "added : konijn" and "discovered: konijn" and sometimes only "added: konijn"

**Comment by gjvanderheiden** [comment] 2024-08-20 14:09
konijn is dutch for Rabbit.

added : konijn
resolved: konijn
added : Woonkamer bridge
added : Bijkeuken_buiten_en_garage bridge
added : boven bridge
added : Keuken bridge
resolved: Woonkamer bridge
resolved: Bijkeuken_buiten_en_garage bridge
resolved: boven bridge
resolved: Keuken bridge
-------------------------------------------------------------
or ("Hup" is the commercial Hunter Douglass thingy):

added : konijn
resolved: konijn
added : Hup
resolved: Hup
resolved: Hup
resolved: Hup
added : Woonkamer bridge
added : Bijkeuken_buiten_en_garage bridge
added : boven bridge
added : Keuken bridge
resolved: Woonkamer bridge
resolved: Bijkeuken_buiten_en_garage bridge
resolved: boven bridge
resolved: Keuken bridge
---------------------------------------
or:
added : Woonkamer bridge
added : Bijkeuken_buiten_en_garage bridge
added : boven bridge
added : Keuken bridge
resolved: Woonkamer bridge
resolved: Bijkeuken_buiten_en_garage bridge
resolved: boven bridge
resolved: Keuken bridge
added : konijn
---------------------------------------------------
The result is always showed quickly, roughly the first second, de rest of the 14 seconds it just waits

**Comment by plotczyktest** [comment] 2024-08-21 12:56
looks like reverting back [275](https://github.com/jmdns/jmdns/pull/275) fixes the issue of resolving services takes quite long time.
Not sure if it is alse the root cause of this "broken ServiceEvent in discovery"

In our case service resolving was taking like 6s for every new service

**Comment by ViToni** [comment] 2024-08-21 14:42
> The result is always showed quickly, roughly the first second, de rest of the 14 seconds it just waits

The respones are expected to be within ~ 1 second:

* [8.1. Probing](https://datatracker.ietf.org/doc/html/rfc6762#section-8.1)
* [14. Considerations for Multiple Interfaces](https://datatracker.ietf.org/doc/html/rfc6762#section-14)

The timeout for queries is suggested to be at most 2-3 seconds:
* [5.1. One-Shot Multicast DNS Queries](https://datatracker.ietf.org/doc/html/rfc6762#section-5.1)

So anything longer than 3 seconds might be not worth it (not talking about continuous scanning here ).

**Comment by joerg1985** [comment] 2024-08-21 22:04
I will create a PR to fix this soon, thanks for looking into this. Currently all unit tests are disabled, this might get a bigger change to enable them again.

**Comment by plotczyktest** [comment] 2024-08-22 05:20
I can confirm that removing this '_' from before domain fixed our long service discovery issue

**Comment by gjvanderheiden** [comment] 2024-08-22 06:49
Yes! Here too. Works on master branch with modified DNSEntry.

**Comment by kaikreuzer** [comment] 2024-08-23 07:27
Fixed by #291.
I will do a new patch release asap.

**Closed by kaikreuzer** 2024-08-23 07:27 UTC

**Comment by kaikreuzer** [comment] 2024-08-23 07:36
Done: https://github.com/jmdns/jmdns/releases/tag/3.5.12

**Comment by melloware** [comment] 2024-09-19 15:37
Fixed broken DNSRecord test with this PR: https://github.com/jmdns/jmdns/pull/294

**Comment by GazimSoliev** [comment] 2024-11-26 17:32
Thanks, now it's fixed
