### ISSUE TITLE
List SubTypes

### ISSUE THREAD

**Issue by vauvenal5** [jmdns/jmdns#39] opened 2015-11-23 11:56 UTC
Hi!

I am experiencing an issue where I can not list sub types like: "something"._sub."type"
list() will always return an empty Array.
However when I do listBySubtype on "type" I get the complete map sorted by the different subtypes.

Can anyone reproduce this?

**Comment by kaikreuzer** [comment] 2016-02-19 17:27
Looks like a duplicate of https://github.com/jmdns/jmdns/issues/20

**Closed by kaikreuzer** 2016-02-19 17:27 UTC
