### ISSUE TITLE
rare NPE in DNSRecordImp$Address.sameValue()

### ISSUE THREAD

**Issue by bubbleguuum** [jmdns/jmdns#44] opened 2016-02-03 12:26 UTC
I got rare crash dumps with this exception:

java.lang.NullPointerException
at javax.jmdns.impl.DNSRecord$Address.sameValue(SourceFile:302)
at javax.jmdns.impl.JmDNSImpl.handleRecord(SourceFile:1359)
at javax.jmdns.impl.JmDNSImpl.handleResponse(SourceFile:1417)
at javax.jmdns.impl.SocketListener.run(SourceFile:61) 

The failure happens at the last line of DNSRecordImp$Address.sameValue(), where in rare case (bogus devices ?) we can get there with either this.getAddress() or address being null:

 return this.getAddress().equals(address.getAddress());

**Comment by kaikreuzer** [comment] 2016-02-19 17:30
Duplicate of https://github.com/jmdns/jmdns/issues/34

**Closed by kaikreuzer** 2016-02-19 17:30 UTC
